// <auto-generated />
using System;
using AllDemo.Data.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllDemo.Models.AcademicYearModel", b =>
                {
                    b.Property<int>("Year_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year_Id"));

                    b.Property<DateOnly?>("End_Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Start_Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Year_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Year_Id");

                    b.ToTable("tblAcademicYear");
                });

            modelBuilder.Entity("AllDemo.Models.AdmissionTypeModel", b =>
                {
                    b.Property<int>("AdmissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionTypeId"));

                    b.Property<string>("AdmissionTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AdmissionTypeId");

                    b.HasIndex("AdmissionTypeName")
                        .IsUnique();

                    b.ToTable("tblAdmissionType");
                });

            modelBuilder.Entity("AllDemo.Models.RoleModel", b =>
                {
                    b.Property<int?>("RollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RollId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollId");

                    b.ToTable("tblRole");
                });

            modelBuilder.Entity("AllDemo.Models.SemesterModel", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Year_Id")
                        .HasColumnType("int");

                    b.HasKey("SemesterId");

                    b.HasIndex("Year_Id");

                    b.ToTable("tblSemester");
                });

            modelBuilder.Entity("AllDemo.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("AllDemo.Models.SemesterModel", b =>
                {
                    b.HasOne("AllDemo.Models.AcademicYearModel", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("Year_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("AllDemo.Models.AcademicYearModel", b =>
                {
                    b.Navigation("Semesters");
                });
#pragma warning restore 612, 618
        }
    }
}
